include:
  - project: 'gitops-demo/infra/templates'
    file: '/terraform.gitlab-ci.yml'


tfsec:
  image: 
    name: wesleydeanflexion/tfsec
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:go/bin/'
  stage: plan
  before_script:
    - echo 0
  script: tfsec .
  only:
    - merge_requests