include:
  - project: 'gitops-demo/infra/templates'
    ref: 9-move-to-open-tofu 
    file: '/terraform.gitlab-ci.yml'

.secrets:
  id_tokens:
      GITOPS_DEMO_VAULT_JWT:
        aud: "GITOPS-DEMO"
  secrets:
    AWS_ACCESS_KEY_ID:
      vault: infrastructure/aws/AWS_ACCESS_KEY_ID@secret
      file: false
    AWS_SECRET_ACCESS_KEY:
      vault: infrastructure/aws/AWS_SECRET_ACCESS_KEY@secret
      file: false
    AWS_REGION:
      vault: infrastructure/aws/AWS_REGION@secret
      file: false
    GITLAB_TOKEN:
      vault: infrastructure/gitlab/GITLAB_TOKEN@secret
      file: false

plan: 
  extends: [.secrets]

apply:
  extends: [.secrets]

destroy:
  extends: [.secrets]